version: '3.18'

networks:
  mynet:
    driver: bridge

services:
  conteiner-dev:
    build:
     context: .
     dockerfile: Dockerfile.remote
    container_name: container_dev
    networks:
      - mynet
    volumes:
      - ".:/app"
    ports:
      - "8082:8082"      

